### ISSUE TITLE
ERROR: Failed building wheel for dm-tree when doing `pip install py_outrider`

### ISSUE THREAD

**Issue by GianArauz** [gagneurlab/py_outrider#1]
### Context
I cloned the `py_outrider` repo and I created a separated conda environment using the `environment.yml` file provided within. I was able to activate such environment as expected just doing `conda activate outrider2`.

###  Problem
I got an error when trying to install `py_outrider` using `pip install py_outrider` (see [outrider2_installation_error.txt](https://github.com/gagneurlab/py_outrider/files/10309489/outrider2_installation_error.txt)). I bump with the same error using `pip install git+https://github.com/gagneurlab/py_outrider.git`.

###  Tried
After searching a bit, I tried `pip install cmake` before retrying `pip install py_outrider` again. Now I got an slightly different error (see [outrider2_installation_error2.txt](https://github.com/gagneurlab/py_outrider/files/10309553/outrider2_installation_error2.txt)). 

###  Need
How could I fix this `py_outrider` installation issue?

###  Thanks
Many thanks in advance for sharing your `py_outrider` tool and devoting time to solve our issues.

**Comment by c-mertes** [comment]
Dear @GianArauz,

as you found already your first error by installing cmake, the second error is still on your side. 

It is still missing a compiler. Hence, can you also install a compiler? 

```
# if you have windows
conda install -c conda-forge m2w64-gcc

# if you are running on linux
conda install -c conda-forge gcc_impl_linux-64
```
Windows: https://anaconda.org/conda-forge/m2w64-gcc
Linux: https://anaconda.org/conda-forge/gcc_impl_linux-64

And then try again to install dm_tree and if this works you can install py_outrider.


### Another option: 

As `dm_tree` is not a direct dependency of `py_outrider` I would try to install everything through conda and then install `py_outrider`. 

can you install the following env `py_outrider_env.yaml`:
```
name: py_outrider
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - anndata>=0.7.0
  - matplotlib>=3.2.1
  - numpy>=1.19.2
  - pandas>=1.1.5
  - pip>=20.3.3
  - scikit-learn>=0.23.1
  - statsmodels>=0.11.1
  - tensorflow>=2.3.0
  - tensorflow-probability>=0.10.0
  - xarray>=0.15.1
  - zarr>=2.3.2
  - pip:
    - nipals>=0.5.2
```

with

```
# install all dependencies
conda env create -f py_outrider_env.yaml

# this should only install py_outrider and nothing else
pip install git+https://github.com/gagneurlab/py_outrider
```

**Comment by GianArauz** [comment]
Dear @c-mertes,

Many thanks for your support! I directly took your 2nd option and everything went smooth:

```
# install all dependencies
conda env create -f py_outrider_env.yaml

# activate the just created py_outrider environment 
conda activate py_outrider

# this should only install py_outrider and nothing else
pip install git+https://github.com/gagneurlab/py_outrider 
```

I have to mention that `Solving environment: done` took a very long time to appear (hours!) in my W10 machine with a freshly new Anaconda installation.

I also suspect that maybe my previous Anaconda installation was messed up and that's the reason why I had problems with the compilers. I don't know for sure...

Thanks again for your time and for sharing `py_outrider` with the community!

Gian.

**Comment by Hoeze** [comment]
@GianArauz you should try [mamba](https://github.com/mamba-org/mamba):
`mamba env create -f py_outrider_env.yaml`
This will speed up your solving to <5mins.

Also, you should consider switching to some Unix-based OS (e.g. Linux, MacOS). Windows is an awful operating system for scientific workloads (no symlinks, does not support process forking, case-insensitive file system, etc.).
